### ISSUE TITLE
Handle token expiration

### ISSUE THREAD

**Issue by hypnoglow** [yieldr/go-auth0#15]
Currently, there is a `StaticTokenSource` created that would never refresh the token. This is ok for **terraform-provider-auth0** and similar apps with short-lived sessions.

However, this library cannot be used in long-running applications, like an http server. Once token expires, all requests would fail, and a new `Management` instance have to be created.

Possible solution: replace `StaticTokenSource` with token source implementing token renewal. I'm not sure if this works out-of-the-box for `client_credentials` grant. Also, there is a [https://godoc.org/golang.org/x/oauth2/clientcredentials](https://godoc.org/golang.org/x/oauth2/clientcredentials) package that might provide an easy solution for this.

---

If you approve the idea, I can dig into it to see if I can provide a solution and submit a PR.

**Comment by alexkappa** [comment]
Hi @hypnoglow, it seems https://godoc.org/golang.org/x/oauth2#Token supports refresh tokens in a way, but we need to receive the token from the Auth0 API.

For this to work, the API needs to be [configured for offline access](https://auth0.com/docs/apis#api-settings).  I tried enabling it, but I [can't seem to find it in my dashboard](https://community.auth0.com/t/where-is-allow-offline-access-option-in-dashboard/7632) and didn't have time to try using the Management API.

If enabling offline access is easily doable, the fix could be pretty straightforward by:
- Adding `RefreshToken` [here](https://github.com/yieldr/go-auth0/blob/master/management/management.go#L63)
- And using the value returned by Auth0 [here](https://github.com/yieldr/go-auth0/blob/master/management/management.go#L156)

**Comment by hypnoglow** [comment]
@alexkappa Refresh token is **not required** for client credentials grant, because you can just get a new access token only with static **client_id** and **client_secret**.  I think this is how client credentials grant supposed to work.

**Comment by alexkappa** [comment]
Indeed, its not required. But what I'm saying is if your Auth0 API is configured with offline mode enabled, [this response](https://github.com/yieldr/go-auth0/blob/master/management/management.go#L149) will contain a `refresh_token` field, which we can directly use with the `StaticTokenSource` and the `oauth2.Client` will take care of re-authenticating using a refresh token without any changes.

**Comment by hypnoglow** [comment]
@alexkappa Sorry, I don't get your point. Technically, you are correct about refresh tokens and offline mode. But this library **go-auth0** uses only [client credentials](https://auth0.com/docs/api/authentication#client-credentials) grant and authenticates against Management API. So refersh token is not involved here.

References:
- https://auth0.com/docs/api-auth/tutorials/client-credentials
- https://auth0.com/docs/tokens/refresh-token/current

> Restrictions
You can only get a Refresh Token if you are implementing: Authorization Code Grant, Authorization Code Grant (PKCE) or Resource Owner Password Grant.

**Comment by alexkappa** [comment]
Ok, I think I understand what you mean. We can't get a refresh_token from Auth0 using client credentials so we'll need to "refresh" the access_token ourselves whenever it expires, is that right?

**Comment by hypnoglow** [comment]
@alexkappa That's correct 👍 

I think https://godoc.org/golang.org/x/oauth2/clientcredentials package should do this job, so we don't need to handle this ourselves. I will try it and see if it works with Auth0, then I share you the results.

**Comment by alexkappa** [comment]
That seems to be used to retrieve a token if I'm not mistaken. I would have loved to use it but the Auth0 response is slightly different and cannot be correctly unmarshalled into an `oauth.Token` (`Expiry` vs `ExpiresIn`). Thats why I had to define auxiliary config and token structs in order to adapt it.

The answer might be in the form of [`TokenSource`](https://godoc.org/golang.org/x/oauth2#TokenSource) however. It uses an initial token and when it becomes invalid, asks for a new one from `src`.
