### ISSUE TITLE
Add the ability to log the Auth0 API calls

### ISSUE THREAD

**Issue by dancrumb** [yieldr/go-auth0#23]
When it comes to debugging one's terraform configuration, it would be great to be able to log the API calls that were being made.

Something simple like endpoint called and data passed would be a real help. Right now, I'm getting 

```
* auth0_client.test_client: 400 Bad Request: Payload validation error: 'Too few properties defined (0), minimum 1'.
```
and it's very hard to understand what I'm missing since I can't see the request

**Comment by alexkappa** [comment]
Hi @dancrumb, you can use the environment variables `TF_LOG=DEBUG` to have terraform print out logging and `AUTH0_DEBUG=1` (or configure the provider with debug enabled) to have the auth0 provider dump requests and responses.
