### ISSUE TITLE
Can not remove all clients from a connection

### ISSUE THREAD

**Issue by mvanderlee** [yieldr/go-auth0#241]
### Description

Setting `c.EnabledClients` to an empty list causes it to be omitted from the actual update request and thus the field is not actually updated.

This is because `omitempty` omits empty slices as well. As found in `EnabledClients []interface{} json:"enabled_clients,omitempty"`.
This appears to be related to https://github.com/golang/go/issues/22480

I'm not familiar with GoLang, but maybe there is a way to omit nil in the `MarshalJSON` function in connection.py?

### Package Version

```
v5.19.2
```

### Affected Resources

* `management.Connection`

### Sample Code

```go
c := &management.Connection{
  EnabledClients = []interface{}
}
err = api.Connection.Update(connId, c, management.Context(ctx))
```

### Expected Behavior

Should set EnabledClients to an empty list. i.e.: disable the connection for all clients

### Actual Behavior

EnabledClients update is ignored, or if it's the only property set, the request actually fails.

### Output

```shell
Error: 400 Bad Request: Payload validation error: 'Too few properties defined (0), minimum 1'
```

### References

https://github.com/golang/go/issues/22480

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
Closed and cloned this issue to https://github.com/auth0/go-auth0/issues/19
